// МАССИВ ТОВАРОВ
const productData = [
    {
        labels: ["new", "hit", "sale"],
        image: "/Plumbing-supple-store.github.io/products/Demm SPIKE.jpg",
        status: "Нет в наличии",
        article: "6810",
        title: "Demm SPIKE Смеситель для раковины на 1отв.,излив: 11,6см с донным клапаном, цвет: ХРОМ",
        collection: "SPIKE",
        priceNew: "15 020",
        priceOld: "20 600",
        typeProduct: "mixers",
        description: "Demm SPIKE Смеситель для раковины на 1отв.,излив: 11,6см с донным клапаном, цвет: ХРОМ",
        color: "Хром",
        characteristics: {
            "Коллекция": "SPIKE",
            "Стиль": "Современный",
            "Вид": "Для раковины",
            "Тип монтажа": "На 1 отверстие",
            "Управление": "Однорычажный",
            "Количество источников": "1"
        },
        kit: ["Смеситель", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["new", "hit"],
        image: "/Plumbing-supple-store.github.io/products/Demm SLEEK.jpg",
        status: "В наличии",
        article: "9918HU",
        title: "Demm SLEEK Смеситель для раковины встраиваемый, с внутренней частью, излив 15см, цвет: НИКЕЛЬ МАТОВЫ",
        collection: "SLEEK",
        priceNew: "28 586",
        priceOld: null,
        typeProduct: "mixers",
        description: "Demm SLEEK Смеситель для раковины встраиваемый, с внутренней частью, излив 15см, цвет: НИКЕЛЬ МАТОВЫЙ", // Уникальное описание
        color: "Никель матовый",
        characteristics: {
            "Коллекция": "SLEEK",
            "Стиль": "Современный",
            "Вид": "Для раковины",
            "Тип монтажа": "Встраиваемый",
            "Управление": "Однорычажный",
            "Тип монтажа": "На 1 отверстие",
            "Количество источников": "1",
        },
        kit: ["Смеситель", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["hit"],
        image: "/Plumbing-supple-store.github.io/products/Demm SPIKE_2.jpg",
        status: "В наличии",
        article: "ACIARIUM INOX",
        title: "Demm SPIKE Смеситель для биде на 1отв. с донным клапаном, цвет: ЧЕРНЫЙ",
        collection: "SPIKE",
        priceNew: "34 500",
        priceOld: null,
        typeProduct: "mixers",
        description: "Коллекция смесителей JAGO от DEMM RUBINETTERIE отличается современным дизайном и надежностью...", // Уникальное описание
        color: "Черный матовый",
        characteristics: {
            "Коллекция": "SPIKE",
            "Стиль": "Современный",
            "Вид": "Для биде",
            "Тип монтажа": "Скрытый монтаж",
            "Управление": "Однорычажный",
            "Количество источников": "1",
        },
        kit: ["Смеситель", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["new", "hit"],
        image: "/Plumbing-supple-store.github.io/products/Demm SLEEK_2.jpg",
        status: "В наличии",
        article: "9914ZRM",
        title: "Demm SLEEK Смеситель для раковины Высокий на 1отв.,излив: 17см с донным клапаном, цвет: РОДИЙ МАТОВЫ",
        collection: "SLEEK",
        priceNew: "32 946",
        priceOld: null,
        typeProduct: "mixers",
        description: "Demm SLEEK Смеситель для раковины Высокий на 1отв.,излив: 17см с донным клапаном, цвет: РОДИЙ МАТОВЫ",
        color: "Родий матовый",
        characteristics: {
            "Коллекция": "SLEEK",
            "Стиль": "Современный",
            "Вид": "Для раковины",
            "Тип монтажа": "Встраиваемый",
            "Управление": "Однорычажный",
            "Тип монтажа": "На 1 отверстие",
            "Количество источников": "1",
        },
        kit: ["Смеситель", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["sale"],
        image: "/Plumbing-supple-store.github.io/products/Demm INCASSO.jpg",
        status: "Нет в наличии",
        article: "16050NU",
        title: "Demm INCASSO Встроенная душевая система Термостатический,на 2 выхода с перекл.,цвет: ЧЕРНЫЙ",
        collection: "INCASSO",
        priceNew: "96 900",
        priceOld: "120 220",
        typeProduct: "shower systems",
        description: "Demm INCASSO Встроенная душевая система Термостатический,на 2 выхода с перекл.,цвет: ЧЕРНЫЙ",
        color: "Черный матовый",
        characteristics: {
            "Коллекция": "INCASSO",
            "Стиль": "Современный",
            "Вид": "Душевая система",
            "Тип монтажа": "Встраиваемый",
            "Управление": "Термостат",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая система", "Монтажная часть", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/Demm INCASSO_2.jpg",
        status: "В наличии",
        article: "16040NU",
        title: "Demm INCASSO Встроенная душевая система с встроенной частью, на 2 выхода с перекл,квадр,цвет: ЧЕРНЫЙ",
        collection: "INCASSO",
        priceNew: "48 450",
        priceOld: null,
        typeProduct: "shower systems",
        description: "Demm INCASSO Встроенная душевая система с встроенной частью, на 2 выхода с перекл,квадр,цвет: ЧЕРНЫЙ",
        color: "Черный матовый",
        characteristics: {
            "Коллекция": "INCASSO",
            "Стиль": "Современный",
            "Вид": "Душевая система",
            "Тип монтажа": "Встраиваемый",
            "Управление": "Однорычажный",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая система", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["new", "hit", "sale"],
        image: "/Plumbing-supple-store.github.io/products/Demm SLEEK_3.jpg",
        status: "В наличии",
        article: "16099",
        title: "Demm SLEEK Смеситель для раковины на 1 отв, цвет: хром",
        collection: "SLEEK",
        priceNew: "43 605",
        priceOld: "50 600",
        typeProduct: "shower systems",
        description: "Demm SLEEK Встроенная душевая система с встроенной частью, на 2 выхода с перекл,квадр,цвет: ЧЕРНЫЙ",
        color: "Хром",
        characteristics: {
            "Коллекция": "SLEEK",
            "Стиль": "Современный",
            "Вид": "Душевая система",
            "Тип монтажа": "Встраиваемый",
            "Управление": "Однорычажный",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая система", "Монтажная часть", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/Demm INCASSO_3.jpg",
        status: "В наличии",
        article: "16040",
        title: "Demm INCASSO Встроенная душевая система с встроенной частью, на 2 выхода с перекл., квадр,цвет: ХРОМ",
        collection: "INCASSO",
        priceNew: "35 853",
        priceOld: null,
        typeProduct: "shower systems",
        description: "Demm INCASSO Встроенная душевая система с встроенной частью, на 2 выхода с перекл., квадр,цвет: ХРОМ",
        color: "Хром",
        characteristics: {
            "Коллекция": "INCASSO",
            "Стиль": "Современный",
            "Вид": "Душевая система",
            "Тип монтажа": "Встраиваемый",
            "Управление": "Однорычажный",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая система", "Монтажная часть", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/Demm DOCCIA_1.jpg",
        status: "Нет в наличии",
        article: "4718CD",
        title: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, круглая, 1 т.к., Хром",
        collection: "DOCCIA",
        priceNew: "49 581",
        priceOld: null,
        typeProduct: "shower racks",
        description: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, круглая, 1 т.к., Хром",
        color: "Хром",
        characteristics: {
            "Коллекция": "DOCCIA",
            "Стиль": "Современный",
            "Вид": "Душевая стойка",
            "Тип монтажа": "Настненный",
            "Управление": "Термостат",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая стойка", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["sale"],
        image: "/Plumbing-supple-store.github.io/products/Demm DOCCIA_2.jpg",
        status: "Нет в наличии",
        article: "15406NU",
        title: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, круглая цвет: ЧЕРНЫЙ",
        collection: "DOCCIA",
        priceNew: "62 985",
        priceOld: "85 220",
        typeProduct: "shower racks",
        description: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, круглая цвет: ЧЕРНЫЙ",
        color: "Черный матовый",
        characteristics: {
            "Коллекция": "DOCCIA",
            "Стиль": "Современный",
            "Вид": "Душевая стойка",
            "Тип монтажа": "Настненный",
            "Управление": "Термостат",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая стойка", "Монтажная часть", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/Demm DOCCIA_3.jpg",
        status: "В наличии",
        article: "15845",
        title: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, квадрат, цвет: ХРОМ",
        collection: "DOCCIA",
        priceNew: "55 556",
        priceOld: null,
        typeProduct: "shower racks",
        description: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, квадрат, цвет: ХРОМ",
        color: "Хром",
        characteristics: {
            "Коллекция": "DOCCIA",
            "Стиль": "Современный",
            "Вид": "Душевая стойка",
            "Тип монтажа": "Настненный",
            "Управление": "Термостат",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая стойка", "Монтажная часть", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/Demm DOCCIA_4.jpg",
        status: "В наличии",
        article: "15845NU",
        title: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, квадрат, цвет: ЧЕРНЫЙ",
        collection: "KUOVADIS",
        priceNew: "67 830",
        priceOld: null,
        typeProduct: "shower racks",
        description: "Demm DOCCIA Душевая стойка термостатическая, с автоматическим переключателем, квадрат, цвет: ЧЕРНЫЙ",
        color: "Черный матовый",
        characteristics: {
            "Коллекция": "DOCCIA",
            "Стиль": "Современный",
            "Вид": "Душевая стойка",
            "Тип монтажа": "Настненный",
            "Управление": "Термостат",
            "Тип монтажа": "На 2 отверстия",
            "Количество источников": "2",
        },
        kit: ["Душевая стойка", "Монтажная часть", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/INCASSO_1.jpg",
        status: "В наличии",
        article: "9516",
        title: "Demm INCASSO Излив на ванну квадратный, 18,8см, цвет: ХРОМ",
        collection: "INCASSO",
        priceNew: "6 137",
        priceOld: null,
        typeProduct: "spouts",
        description: "Demm INCASSO Излив на ванну квадратный, 18,8см, цвет: ХРОМ",
        color: "Хром",
        characteristics: {
            "Коллекция": "INCASSO",
            "Стиль": "Современный",
            "Вид": "Излив",
            "Тип монтажа": "Настненный",
            "Тип крепления": "На 1 отверстие",
            "Количество источников": "1",
        },
        kit: ["Излив", "Монтажная часть", "Инструкция"]
    },
    {
        labels: ["new", "hit"],
        image: "/Plumbing-supple-store.github.io/products/DEMM_3.webp",
        status: "В наличии",
        article: "161",
        title: "Донный клапан для раковины CLICK-CLACK квадратный без перелива Demm, цвет хром",
        collection: "DEMM",
        priceNew: "6 100",
        priceOld: null,
        typeProduct: "accessories",
        description: "Донный клапан для раковины CLICK-CLACK квадратный без перелива Demm, цвет хром",
        color: "Хром",
        characteristics: {
            "Коллекция": "DEMM",
            "Стиль": "Современный",
            "Вид": "Душевая стойка",
            "Тип монтажа": "Для раковины",
        },
        kit: ["Донный клапан", "Инструкция"]
    },
    {
        labels: [],
        image: "/Plumbing-supple-store.github.io/products/DEMM_2.webp",
        status: "В наличии",
        article: "15421",
        title: "Душевой шланг растягивающийся 150 см “1/2” дюйма Demm",
        collection: "DEMM",
        priceNew: "1 700",
        priceOld: null,
        typeProduct: "accessories",
        description: "Душевой шланг растягивающийся 150 см “1/2” дюйма Demm",
        color: "Сталь",
        characteristics: {
            "Коллекция": "DEMM",
            "Стиль": "Современный",
            "Вид": "Душевой шланг",
            "Материал": "Нержавеющая сталь",
        },
        kit: ["Душевой шланг", "Инструкция"]
    },
    {
        labels: ["hit"],
        image: "/Plumbing-supple-store.github.io/products/Demm_1.webp",
        status: "В наличии",
        article: "4262ZB",
        title: "Выпуск для шланга с держателем “1/2” — “1/2” Demm, латунь, цвет матовое золото",
        collection: "Demm",
        priceNew: "8 000",
        priceOld: null,
        typeProduct: "accessories",
        description: "Выпуск для шланга с держателем “1/2” — “1/2” Demm, латунь, цвет матовое золото",
        color: "Матовое золото",
        characteristics: {
            "Коллекция": "Demm",
            "Стиль": "Современный",
            "Вид": "Выпуск для шланга с держателем",
            "Материал": "Латунь",
        },
        kit: ["Выпуск для шланга с держателем", "Инструкция"]
    },
];

